### ISSUE TITLE
Clarification for Mini Project Presentations

### ISSUE THREAD

**Issue by DeliciousRocks** [fdac21/news#5]
Based on your recent update to News, the  Mini Project presentations are NOT today but are in-person on the 21st.  

For those of us who are presenting, will we need to hook our machines up to the projector, or should what we intend to present be sent to you so that there aren't any technical difficulties?

**Comment by audrism** [comment]
Yes, I think it would be better to present in person. 

I do expect you to share your presentation over zoom (I will display it in the class via projector)
for three reasons:

1. Speed of switching.
2. Sharing with others who could not come
3. Recording

**Comment by DeliciousRocks** [comment]
Okay! Thank you for the clarification on the logistics of the presentations.
